# this  is workflow name
name: hello workflow

on:
  push:
    branches: [main]
    paths:
    - '**.html'
jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:
        - name: say hello to users
          run: echo "hello Dost"
         
        - name: say hello to username
          run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version
        run: docker --version && python --version
        
