name: Portfolio 

on:
  push: 
    branches: [main]

permissions:
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url}}

    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name:  setup github pages
        uses: actions/configure-pages@v4

      - name: upload static pages
        uses: actions/upload-pages-artifact@v4

      - name: upload static pages
        uses: actions/deploy-pages@v4

